import { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { usePatient } from '@/contexts/PatientContext';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Download, UserPlus, AlertTriangle, CheckCircle, AlertCircle, Loader2, Activity } from 'lucide-react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import {
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from 'recharts';
import DynamicBackground from './DynamicBackground';
import AppHeader from './AppHeader';
import MedicalReceipt, { ReceiptData } from './MedicalReceipt';

interface ResultsDashboardProps {
  onConsultSpecialist: () => void;
  onNewPatient?: () => void;
}

const ResultsDashboard = ({ onConsultSpecialist, onNewPatient }: ResultsDashboardProps) => {
  /* eslint-disable @typescript-eslint/no-unused-vars */
  const { predictionResult, patientData, resetPatientData } = usePatient();
  const [isDownloading, setIsDownloading] = useState(false);
  const [patientNote, setPatientNote] = useState("");
  const receiptRef = useRef<HTMLDivElement>(null);

  const handleNewPatient = () => {
    resetPatientData();
    onNewPatient?.();
  };

  if (!predictionResult) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  const { prediction: level, confidence, dashboard, recommendations, diet, plot_url } = predictionResult;

  // Calculate a visual score based on confidence and level
  let score = 0;
  if (level === 'High') score = Math.round(confidence);
  else if (level === 'Medium') score = Math.round(40 + (confidence / 2));
  else score = Math.round(100 - confidence);
  if (score < 0) score = 0;

  // Basic Safety Check
  const safeDashboard = dashboard || { radar: { labels: [], data: [] }, bar: { labels: [], data: [] } };

  // Radar Chart Data
  const radarData = (safeDashboard.radar.labels || []).map((label, i) => ({
    subject: label,
    A: (safeDashboard.radar.data || [])[i] || 0
  }));

  // Bar Chart Data
  const barData = (safeDashboard.bar.labels || []).map((label, i) => ({
    name: label,
    value: Math.abs((safeDashboard.bar.data || [])[i] || 0),
    critical: ((safeDashboard.bar.data || [])[i] || 0) > 0
  }));

  const getRiskIcon = () => {
    switch (level) {
      case 'Low':
        return <CheckCircle className="w-12 h-12 text-particle-safe" />;
      case 'Medium':
        return <AlertCircle className="w-12 h-12 text-yellow-500" />;
      case 'High':
        return <AlertTriangle className="w-12 h-12 text-destructive" />;
    }
  };

  const getRiskColor = () => {
    switch (level) {
      case 'Low':
        return 'text-particle-safe';
      case 'Medium':
        return 'text-yellow-500';
      case 'High':
        return 'text-destructive';
    }
  };

  const doctorNote = `Patient Assessment Summary for ${patientData.name || 'Patient'}:

Based on the comprehensive risk analysis, the patient shows a ${level.toLowerCase()} risk profile.

Recommendations:
${(recommendations || []).map(r => `• ${r}`).join('\n')}

This assessment is generated by LungVision AI and should be reviewed by a qualified healthcare professional.`;

  const handleDownload = async () => {
    if (!receiptRef.current) return;
    setIsDownloading(true);

    try {
      const canvas = await html2canvas(receiptRef.current, {
        scale: 2, // High resolution
        useCORS: true,
        backgroundColor: '#ffffff'
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;

      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgX = (pdfWidth - imgWidth * ratio) / 2;
      const imgY = 0;

      pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth * ratio, imgHeight * ratio);
      pdf.save(`LungVision-Report-${patientData.name || 'Patient'}.pdf`);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
    } finally {
      setIsDownloading(false);
    }
  };

  // Prepare data for the receipt
  const receiptData: ReceiptData = {
    patientNam: patientData.name || 'Unknown Patient',
    date: new Date().toLocaleDateString(),
    riskLevel: level as 'Low' | 'Medium' | 'High',
    riskScore: score,
    consultationId: Math.random().toString(36).substr(2, 9).toUpperCase(),
    doctorNote: doctorNote,
    userNote: patientNote,
    plot_url: plot_url,
    radarData: dashboard?.radar?.labels.map((label, i) => ({
      subject: label,
      A: dashboard.radar.data[i],
      B: [100, 100, 100, 100, 100][i], // Perfect health baseline
      fullMark: 100
    })) || [],
    barData: dashboard?.bar?.labels.map((label, i) => ({
      name: label,
      value: dashboard.bar.data[i],
      critical: Math.abs(dashboard.bar.data[i]) > 1.5
    })) || [],
    diet: diet, // Pass full diet object
    recommendations: recommendations, // Pass recommendations array
    vitals: []
  };

  return (
    <div className="min-h-screen relative">
      <DynamicBackground step={7} />

      <AppHeader showNewPatient onNewPatient={handleNewPatient} />

      <div className="relative z-10 container max-w-6xl mx-auto px-4 pt-24 pb-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          {/* Header */}
          <div className="text-center space-y-2">
            <h1 className="text-3xl font-bold text-foreground">Analysis Results</h1>
            <p className="text-muted-foreground">
              Comprehensive risk assessment for {patientData.name || 'Patient'}
            </p>
          </div>


          {/* Main Grid */}
          <div className="grid md:grid-cols-12 gap-6 mb-8">
            {/* Predicted Risk Card */}
            <div className="md:col-span-4 h-full">
              <Card className="h-full border-0 shadow-lg overflow-hidden flex flex-col bg-transparent">
                <div
                  className="p-3 text-center text-white font-bold uppercase tracking-wider text-sm backdrop-blur-md"
                  style={{ backgroundColor: `${diet.color}66` }}
                >
                  Predicted Risk
                </div>
                <div className="p-6 text-center flex-1 flex flex-col justify-center items-center bg-white/40 dark:bg-[#27293d]/40 backdrop-blur-md">
                  <h1 className="text-6xl font-black mb-4" style={{ color: diet.color }}>
                    {level}
                  </h1>
                  <span className="inline-block bg-zinc-800 text-white rounded-full px-4 py-1 text-sm font-semibold mb-6">
                    Confidence: {confidence}%
                  </span>

                  <div className="w-full text-left bg-zinc-50/50 dark:bg-[#1e1e2f]/50 border border-zinc-200 dark:border-zinc-700 p-4 rounded-md flex-1 flex flex-col overflow-y-auto">
                    {/* Diet Section */}
                    <div className="mb-6">
                      <h6 className="font-bold text-zinc-500 text-xs uppercase tracking-wider mb-3 border-b border-zinc-200 dark:border-zinc-700 pb-2">
                        Clinical Assessment & Diet
                      </h6>
                      <div className="space-y-2">
                        {diet.plain_text.split('. ').map((point, i) => point.trim() && (
                          <div key={i} className="flex items-start gap-2">
                            <span className="text-emerald-500 text-xs mt-0.5">●</span>
                            <span className="text-zinc-800 dark:text-zinc-200 text-xs leading-relaxed">{point.trim().replace('.', '')}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Moved AI Recommendations */}
                    <div>
                      <h6 className="font-bold text-emerald-500 text-xs uppercase tracking-wider mb-3 border-b border-emerald-500/20 pb-2 flex items-center gap-2">
                        <CheckCircle className="w-3 h-3" /> AI Recommendations
                      </h6>
                      <div className="space-y-2">
                        {(recommendations || []).map((r, i) => (
                          <div key={i} className="flex items-start gap-2 bg-emerald-500/5 p-2 rounded border border-emerald-500/10">
                            <CheckCircle className="w-3 h-3 text-emerald-500 mt-0.5 shrink-0" />
                            <span className="text-zinc-700 dark:text-zinc-300 text-[10px] leading-tight">{r}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </Card>
            </div>

            {/* Deep Logic Analysis (Image/Report) */}
            <div className="md:col-span-5 h-full">
              <Card className="h-full border-0 shadow-lg flex flex-col overflow-hidden bg-transparent">
                <div className="p-3 bg-white/40 dark:bg-[#27293d]/40 border-b border-zinc-100 dark:border-zinc-700 font-bold text-center text-zinc-700 dark:text-zinc-200 uppercase tracking-wide text-sm backdrop-blur-md">
                  Deep Logic Analysis
                </div>
                <div className="p-6 bg-white/40 dark:bg-[#27293d]/40 flex-1 flex flex-col items-center justify-center text-center backdrop-blur-md">
                  {plot_url ? (
                    <img
                      src={`data:image/png;base64,${plot_url}`}
                      alt="Deep Logic Analysis"
                      className="w-full h-auto rounded border border-zinc-200 dark:border-zinc-700 mb-4 shadow-sm"
                    />
                  ) : (
                    <div className="w-full bg-zinc-100/50 dark:bg-[#1e1e2f]/50 rounded border border-zinc-200 dark:border-zinc-700 p-8 mb-4 flex items-center justify-center text-zinc-400 flex-1">
                      <div className="text-center">
                        <AlertTriangle className="w-12 h-12 mx-auto mb-2 opacity-20" />
                        <span className="text-xs uppercase font-bold tracking-widest">Visual Graph Unavailable</span>
                      </div>
                    </div>
                  )}

                  <Button
                    variant="outline"
                    className="w-full border-destructive text-destructive hover:bg-destructive hover:text-white font-bold uppercase tracking-wide text-xs h-10 gap-2"
                    onClick={handleDownload}
                    disabled={isDownloading}
                  >
                    {isDownloading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                    Download Full Report (w/ Graphs)
                  </Button>
                </div>
              </Card>
            </div>

            {/* Note To Doctor */}
            <div className="md:col-span-3 h-full">
              <Card className="h-full border-0 shadow-lg flex flex-col overflow-hidden bg-transparent">
                <div className="p-3 bg-zinc-600/40 backdrop-blur-md text-white font-bold text-center uppercase tracking-wide text-sm">
                  A Note To Doctor
                </div>
                <div className="p-4 bg-white/40 dark:bg-[#27293d]/40 flex-1 backdrop-blur-md">
                  <label className="text-[10px] uppercase font-bold text-zinc-400 mb-2 block">Express Your Feelings:</label>
                  <Textarea
                    value={patientNote}
                    onChange={(e) => setPatientNote(e.target.value)}
                    className="w-full h-[calc(100%-80px)] bg-zinc-50/50 dark:bg-[#1e1e2f]/50 border-zinc-200 dark:border-zinc-700 resize-none text-xs leading-relaxed mb-2"
                    placeholder="Example: Feeling of light chest pain at night..."
                  />
                  <Button
                    size="sm"
                    className="w-full bg-zinc-700 hover:bg-zinc-600 text-white h-8 text-xs uppercase tracking-wider font-bold"
                    onClick={() => { /* Mock Save for now, effectively saved in state */ }}
                  >
                    Save Note
                  </Button>
                </div>
              </Card>
            </div>
          </div>

          {/* Live Diagnostic Dashboard (Dark Section) */}
          <div className="bg-[#1e1e2f]/60 backdrop-blur-md text-white rounded-xl shadow-2xl border border-[#2d2d44] p-6 mb-8">
            <div className="flex justify-between items-center mb-6">
              <h5 className="font-bold text-lg flex items-center gap-2">
                <Activity className="w-5 h-5 text-[#00f2c3]" />
                Live Diagnostic Dashboard
              </h5>
              <span className="bg-destructive text-white text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-widest">
                Live Analytics
              </span>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {/* Chart 1: Radar */}
              <div className="bg-[#27293d] rounded-lg border border-[#383a50] p-4 shadow-lg flex flex-col hover:-translate-y-1 transition-transform duration-200">
                <div className="text-[#aab4c3] text-[10px] font-bold uppercase tracking-widest text-center mb-4">
                  Lifestyle Fingerprint
                </div>
                <div className="h-48 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <RadarChart data={radarData}>
                      <PolarGrid stroke="rgba(255,255,255,0.05)" />
                      <PolarAngleAxis dataKey="subject" tick={{ fill: '#aab4c3', fontSize: 9, fontWeight: 700 }} />
                      <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                      <Radar name="Patient" dataKey="A" stroke="#00f2c3" strokeWidth={2} fill="rgba(0, 242, 195, 0.2)" />
                      <Radar name="Healthy" dataKey="B" stroke="rgba(255,255,255,0.3)" strokeWidth={1} strokeDasharray="5 5" fill="transparent" />
                    </RadarChart>
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Chart 2: Waterfall (Simulated with Bar) */}
              <div className="bg-[#27293d] rounded-lg border border-[#383a50] p-4 shadow-lg flex flex-col hover:-translate-y-1 transition-transform duration-200">
                <div className="text-[#aab4c3] text-[10px] font-bold uppercase tracking-widest text-center mb-4">
                  Cumulative Risk Flow
                </div>
                <div className="h-48 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={barData} layout="vertical">
                      <XAxis type="number" hide />
                      <YAxis dataKey="name" type="category" width={80} tick={{ fill: '#aab4c3', fontSize: 9 }} axisLine={false} tickLine={false} interval={0} />
                      <Tooltip
                        contentStyle={{ backgroundColor: '#1e1e2f', border: '1px solid #383a50', color: '#fff' }}
                        itemStyle={{ color: '#00f2c3' }}
                      />
                      <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                        {barData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.critical ? '#ff0055' : '#00f2c3'} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Chart 3: Horizontal Bar */}
              <div className="bg-[#27293d] rounded-lg border border-[#383a50] p-4 shadow-lg flex flex-col hover:-translate-y-1 transition-transform duration-200">
                <div className="text-[#aab4c3] text-[10px] font-bold uppercase tracking-widest text-center mb-4">
                  Key Risk Drivers
                </div>
                <div className="h-48 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={barData} layout="vertical">
                      <XAxis type="number" hide />
                      <YAxis dataKey="name" type="category" width={80} tick={{ fill: '#aab4c3', fontSize: 9 }} axisLine={false} tickLine={false} />
                      <Tooltip
                        contentStyle={{ backgroundColor: '#1e1e2f', border: '1px solid #383a50', color: '#fff' }}
                        cursor={{ fill: 'rgba(255,255,255,0.05)' }}
                      />
                      <Bar dataKey="value" barSize={12} radius={[0, 4, 4, 0]}>
                        {barData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.critical ? '#ff0055' : '#00f2c3'} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          </div>



          {/* Action Buttons */}
          <div className="flex justify-between items-center pt-8 border-t border-zinc-200 dark:border-zinc-700">
            <Button
              variant="outline"
              className="px-8 rounded-full border-zinc-300 text-zinc-500 hover:bg-zinc-100 dark:border-zinc-600 dark:text-zinc-400"
              onClick={handleNewPatient}
            >
              Back
            </Button>
            <Button
              onClick={onConsultSpecialist}
              className="px-10 py-6 rounded-full shadow-lg text-lg font-bold bg-primary hover:bg-primary/90"
            >
              Consult Specialist
            </Button>
          </div>
        </motion.div>
      </div>

      {/* Hidden container for generating PDF */}
      <div style={{ position: 'absolute', top: '-9999px', left: '-9999px' }}>
        <MedicalReceipt ref={receiptRef} data={receiptData} />
      </div>
    </div>
  );
};

export default ResultsDashboard;
