import { motion } from 'framer-motion';
import { usePatient } from '@/contexts/PatientContext';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Download, UserPlus, AlertTriangle, CheckCircle, AlertCircle } from 'lucide-react';
import {
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from 'recharts';
import DynamicBackground from './DynamicBackground';
import AppHeader from './AppHeader';

interface ResultsDashboardProps {
  onConsultSpecialist: () => void;
  onNewPatient?: () => void;
}

const ResultsDashboard = ({ onConsultSpecialist, onNewPatient }: ResultsDashboardProps) => {
  const { patientData, calculateRisk, resetPatientData } = usePatient();

  const handleNewPatient = () => {
    resetPatientData();
    onNewPatient?.();
  };
  const { level, score } = calculateRisk();

  // Radar Chart Data - Lifestyle Fingerprint
  const radarData = [
    { subject: 'Smoking', A: patientData.isSmoker ? (patientData.smokingIntensity * 11) : 0 },
    { subject: 'Alcohol', A: patientData.alcoholUse * 11 },
    { subject: 'Diet', A: (10 - patientData.balancedDiet) * 11 },
    { subject: 'Obesity', A: patientData.obesityLevel * 11 },
    { subject: 'Environment', A: patientData.airPollution * 11 },
    { subject: 'Genetics', A: patientData.geneticRisk ? 80 : 10 },
  ];

  // Bar Chart Data - Top Risk Drivers
  const barData = [
    { name: 'Blood Cough', value: patientData.coughingBlood * 11, critical: true },
    { name: 'Chest Pain', value: patientData.chestPain * 11, critical: false },
    { name: 'Breath', value: patientData.shortnessOfBreath * 11, critical: false },
    { name: 'Weight Loss', value: patientData.weightLoss * 11, critical: false },
    { name: 'Fatigue', value: patientData.fatigue * 11, critical: false },
  ].sort((a, b) => b.value - a.value);

  const getRiskIcon = () => {
    switch (level) {
      case 'Low':
        return <CheckCircle className="w-12 h-12 text-particle-safe" />;
      case 'Medium':
        return <AlertCircle className="w-12 h-12 text-yellow-500" />;
      case 'High':
        return <AlertTriangle className="w-12 h-12 text-destructive" />;
    }
  };

  const getRiskColor = () => {
    switch (level) {
      case 'Low':
        return 'text-particle-safe';
      case 'Medium':
        return 'text-yellow-500';
      case 'High':
        return 'text-destructive';
    }
  };

  const doctorNote = `Patient Assessment Summary for ${patientData.name || 'Patient'}:

Based on the comprehensive risk analysis, the patient shows a ${level.toLowerCase()} risk profile with a calculated score of ${score}%.

Key Observations:
${patientData.isSmoker ? '• Active smoker with ' + patientData.yearsOfSmoking + ' years of smoking history' : '• Non-smoker status is a positive factor'}
${patientData.coughingBlood > 3 ? '• Hemoptysis reported - requires immediate clinical attention' : ''}
${patientData.shortnessOfBreath > 5 ? '• Significant respiratory distress noted' : ''}
${patientData.geneticRisk ? '• Family history of lung cancer present' : ''}
${patientData.chronicLungDisease ? '• Existing chronic lung disease' : ''}

Recommendations:
${level === 'High' ? '• Urgent pulmonary consultation recommended\n• Consider CT scan screening\n• Lifestyle modification program essential' : 
  level === 'Medium' ? '• Schedule follow-up in 3 months\n• Monitor symptoms closely\n• Consider lifestyle modifications' :
  '• Continue healthy lifestyle practices\n• Annual check-up recommended\n• Stay vigilant for new symptoms'}

This assessment is generated by LungVision AI and should be reviewed by a qualified healthcare professional.`;

  return (
    <div className="min-h-screen relative">
      <DynamicBackground step={6} />
      
      <AppHeader showNewPatient onNewPatient={handleNewPatient} />

      <div className="relative z-10 container max-w-6xl mx-auto px-4 pt-24 pb-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          {/* Header */}
          <div className="text-center space-y-2">
            <h1 className="text-3xl font-bold text-foreground">Analysis Results</h1>
            <p className="text-muted-foreground">
              Comprehensive risk assessment for {patientData.name || 'Patient'}
            </p>
          </div>

          {/* Main Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Prediction Card */}
            <Card className="glass-card p-6 md:col-span-2 lg:col-span-1">
              <div className="text-center space-y-4">
                <h3 className="text-lg font-semibold text-muted-foreground">Risk Level</h3>
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: 'spring', delay: 0.2 }}
                  className="flex flex-col items-center gap-4"
                >
                  {getRiskIcon()}
                  <span className={`text-5xl font-bold ${getRiskColor()}`}>
                    {level}
                  </span>
                  <div className="w-full bg-muted rounded-full h-3">
                    <motion.div
                      className={`h-3 rounded-full ${
                        level === 'Low' ? 'bg-particle-safe' : 
                        level === 'Medium' ? 'bg-yellow-500' : 
                        'bg-destructive'
                      }`}
                      initial={{ width: 0 }}
                      animate={{ width: `${score}%` }}
                      transition={{ delay: 0.5, duration: 1 }}
                    />
                  </div>
                  <p className="text-2xl font-medium text-foreground">{score}%</p>
                </motion.div>
              </div>
            </Card>

            {/* Radar Chart - Lifestyle Fingerprint */}
            <Card className="glass-card p-6">
              <h3 className="text-lg font-semibold text-muted-foreground mb-4">Lifestyle Fingerprint</h3>
              <ResponsiveContainer width="100%" height={200}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="hsl(var(--border))" />
                  <PolarAngleAxis 
                    dataKey="subject" 
                    tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} 
                  />
                  <PolarRadiusAxis 
                    angle={30} 
                    domain={[0, 100]} 
                    tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }}
                  />
                  <Radar
                    name="Risk"
                    dataKey="A"
                    stroke="hsl(var(--primary))"
                    fill="hsl(var(--primary))"
                    fillOpacity={0.3}
                  />
                </RadarChart>
              </ResponsiveContainer>
            </Card>

            {/* Bar Chart - Top Risk Drivers */}
            <Card className="glass-card p-6">
              <h3 className="text-lg font-semibold text-muted-foreground mb-4">Top Risk Drivers</h3>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={barData} layout="vertical">
                  <XAxis type="number" domain={[0, 100]} hide />
                  <YAxis 
                    type="category" 
                    dataKey="name" 
                    tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }}
                    width={80}
                  />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: 'hsl(var(--card))', 
                      border: '1px solid hsl(var(--border))',
                      borderRadius: '8px'
                    }}
                  />
                  <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                    {barData.map((entry, index) => (
                      <Cell 
                        key={`cell-${index}`} 
                        fill={entry.critical ? 'hsl(var(--destructive))' : 'hsl(var(--primary))'} 
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </Card>
          </div>

          {/* Doctor's Note */}
          <Card className="glass-card p-6">
            <h3 className="text-lg font-semibold text-muted-foreground mb-4">Doctor's Note</h3>
            <Textarea
              readOnly
              value={doctorNote}
              className="min-h-[250px] bg-transparent resize-none font-mono text-sm"
            />
          </Card>

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button variant="outline" className="gap-2">
              <Download className="w-4 h-4" />
              Download Report
            </Button>
            <Button onClick={onConsultSpecialist} className="gap-2 glow">
              <UserPlus className="w-4 h-4" />
              Consult Specialist
            </Button>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default ResultsDashboard;
